# Generated by Django 3.0.4 on 2020-04-26 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
